name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Lua Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lua and Luarocks
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v5
        with:
          luarocksVersion: "3.9.2"

      - name: Install busted
        run: |
          luarocks install busted

      - name: Run tests
        run: |
          make test
